### ISSUE TITLE
Request for help, how to get the original data of items?

### ISSUE THREAD

**Issue by lklk6644** [Wacky-Mole/WackysDatabase#11]
Hi bro,

How to get the original data of items?
It is first time to trying mod edit, my goal is items translation
Checked FAQ, I just need to adjust there 2 line, do not need adjust others,
-------------------
m_name: TO OTHER TEXT
m_description: TO OTHER TEXT
-------------------

Do not know the items original data, e.g IronSword, just change the name IronSword, do not adjust the damage, durability, etc.
Looking forward to getting your help, Thx!

**Comment by Wacky-Mole** [comment]
The only thing required is name, and m_weight so...

name: SwordIron
m_weight: 0.8
m_name: $item_sword_iron
m_description: $item_sword_iron_description

Try to use quotes to change stuff " My new name" and please use the yaml validator.
