### ISSUE TITLE
Null Value Stops Execution - wackydb_all_items

### ISSUE THREAD

**Issue by Yourname942** [Wacky-Mole/WackysDatabase#13]
This null value stops the execution, and I cannot save any of the items after this one null value.
![20231229154616_1](https://github.com/Wacky-Mole/WackysDatabase/assets/58750222/92b8e7c8-6d07-497d-bd28-df1ccd1cd7ec)

**List of Mods**
![Mods](https://github.com/Wacky-Mole/WackysDatabase/assets/58750222/875e84da-bac1-48ac-8e6e-ec78c2823930)

**Steps to Reproduce**
  1. Install these mods via r2Modman
  2. launch the game
  3. start a new character/ hammerworld
  4. open F5 console
  5. run the command `wackydb_all_items`
_Observe that the null value stops the execution and you don't get to save the remaining items_

**Expected**
All of the items will be saved

**Actual**
Items up to a null value will be saved and the execution stops.

**Comment by Wacky-Mole** [comment]
Fixed in 2.2.1
