### ISSUE TITLE
Enemy Attacks/Events/States are saved as items?

### ISSUE THREAD

**Issue by Yourname942** [Wacky-Mole/WackysDatabase#14]
This issue is somewhat blocked by https://github.com/Wacky-Mole/WackysDatabase/issues/13
(at least if you are using these mods below)

For some reason running the command `wackydb_all_items` is saving non-items as items? Specifically, enemy attacks, events, or states? 
Like stomp, firebreath, attack, etc.

**List of Mods**
![Mods](https://github.com/Wacky-Mole/WackysDatabase/assets/58750222/2931432a-a3cb-4d42-bd9f-bc7604c2b837)

**Steps to Reproduce**
  1. Install these mods via r2Modman
  2. launch the game
  3. start a new character/ hammerworld
  4. open F5 console
  5. run the command wackydb_all_items
  Observe that there are non-items in the items list (again, if you are using the mods listed above, then you will be blocked until the null issue is resolved)

**Expected**
Only Items will be saved

**Actual**
Non-Items are being saved in the items list

**Comment by Wacky-Mole** [comment]
This is an intended effect, some people edit the attacks, to edit mobs. Thank you for the bug reports.

**Comment by Yourname942** [comment]
Is it possible to create a separate all items command that excludes enemy attacks/etc.?

**Comment by Yourname942** [comment]
> This is an intended effect, some people edit the attacks, to edit mobs. Thank you for the bug reports.


Is it possible to create a separate all items command that excludes enemy attacks/etc.?
