### ISSUE TITLE
Cloning Materials results in darker Materials

### ISSUE THREAD

**Issue by Lughbaloo** [Wacky-Mole/WackysDatabase#17]
When running `wackydb_save_material [materialname]`, the expected behavior is that the material is cloned from the existing material to be an exact copy. Applying this new material to an item without any alteration to the Material file will result in an item that is overall darker than using the donor material. It's as if the cloned textures are overlaying the donor textures, resulting in a darker texture.

To further test this, I cloned a cloned material, and cloned that material again, and applied it to weapons each step of the way. At every interval the weapon got darker and darker. This example is using `meteorite` as the material.

![image](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/bf7762c7-21a4-4aab-83ba-3159b6f7ad5a)
![image](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/da46eaf7-0d59-43b0-adc2-58de933d70bf)
![image](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/d0c26a6d-2f11-46db-b737-3f33ec0199b9)

**Comment by Lughbaloo** [comment]
It might be an issue with a linear color space being interpreted as SRGB when the material is cloned, just a guess.


![1_-_0xbROb4jjFP8C_MpZnmw](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/70bda360-8e72-49bd-81a1-7f3291231449)

![firefox_2024-06-24_22-44-39](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/c17660ed-8d06-4e3f-8e36-9ab6544fad5b)

**Comment by Lughbaloo** [comment]
Some further research found interesting results.

The albedo map derived from Wacky's clone command produces a much darker image than one derived straight from Unity.

These are both from the weapon Krom. 
![krom_d](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/5ec810ce-9e61-437b-8ad3-168c4c1db596)
![krom_d](https://github.com/Wacky-Mole/WackysDatabase/assets/44557173/b6e09ccb-2401-47b6-b814-e88b4f86b7b8)

**Comment by Wacky-Mole** [comment]
Issue should be fixed in latest version
