### ISSUE TITLE
Hello! Can I add a command or function to export all configuration files by module ID?

### ISSUE THREAD

**Issue by aopkcn** [Wacky-Mole/WackysDatabase#2]
Hello! Can I add a command or function to export all configuration files by module ID?

**Comment by Wacky-Mole** [comment]
Sure.  We are trying to work towards finishing ymal2 branch for wackydb 2.0. But I'll push it in master if you get it done.
-WM

**Comment by Wacky-Mole** [comment]
2.0 beta
