### ISSUE TITLE
WackysDB causing connection problems

### ISSUE THREAD

**Issue by Mortiseraphim** [Wacky-Mole/WackysDatabase#3]
A friend and I are trying to play 'Epic Valheim', which naturally includes wacky's database, via a listen server. IE: non-dedicated. me hosting and he joins via steam. The issue is, he continually gets this error:

"mod wackysdatabase requires a maximum of 0.0.1, current version 1.2.7"

We have tried disabling WackysDB in the mod list (using thunderstore.io launcher) which solves the issue, but unfortunately it breaks a load of recipes and progression related items in the process; so that won't work. I have also set the config to NOT force server sync to no avail. The last thing I see when I load into map is "[Warning:WackysDatabase] You will be kicked from multiplayer servers! 0.0.1" which consequently is the version my friend is being told he needs. I see no setting in the config to change this requirement. 

My question is, how do I go about still using the mod, which is required for all the recipes to function properly, but still be able to play together? Is there a work around? A setting I've missed in the long list of config files it touches? 
![image](https://user-images.githubusercontent.com/116059859/196357658-ba5c49f1-4365-4c34-8bef-99c5cdf130c7.png)
![image](https://user-images.githubusercontent.com/116059859/196357726-173191d4-bb03-4ddd-bb35-2c546e92841e.png)

**Comment by Mortiseraphim** [comment]
Forgot to mention that crossplay is OFF since we have tried with crossplay on and this error occurs:
![image](https://user-images.githubusercontent.com/116059859/196360291-5300b4ea-8b0e-4dc5-8293-267046ce90a1.png)

**Comment by Wacky-Mole** [comment]
Should be fixed in 1.2.8
