### ISSUE TITLE
Reload database every 2 min

### ISSUE THREAD

**Issue by SpanisHammer** [Wacky-Mole/WackysDatabase#4]
First of all thanks to Wackymole and AzumattDev for creating this mod.
The problem I have is that almost every 2 minutes the mod reloads the database and freezes the game in the process, I have tried to change the settings but there is no way, any suggestions?

**Comment by Wacky-Mole** [comment]
I know some Linux dockers sometimes trigger the autoreload, but unless you are changing a file or doing wackydb_reload, it should not.

**Comment by SpanisHammer** [comment]
I have created some files and modified others of the Boneapetti translation, I have tried to remove the translation of my language because it was in the item/recipe/pieces folders, it has improved because it no longer loads so many objects but it continues giving this message.

**Comment by SpanisHammer** [comment]
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase
[Debug  :WackysDatabase] CustomSyncEventDetected was called 
[Debug  :WackysDatabase] Synced String was blank 
Received 0 configs and 1 custom values from the server for mod WackysDatabase

**Comment by Wacky-Mole** [comment]
2.0 will have a feature to stop the autoreload on servers.

**Comment by SpanisHammer** [comment]
That's great news and I think a great solution, I'm a big fan of Wackydatabasa and I hope there won't just be a 2.0 version.

**Comment by Wacky-Mole** [comment]
Added FileWatcher config to 1.4.3, will be in 2.0 with a remote admin reload command
