### ISSUE TITLE
Duplicated items on items existing/clones

### ISSUE THREAD

**Issue by JOHNN1Ez** [Wacky-Mole/WackysDatabase#9]
Hey!

We have a problem *(on WackyDB and WackyDB 2.0 Beta b16)* which is: every items which is modified AND every clone has double recipe in workbench, forge and so on..

It's a bit annoying because we have a lot of items so... It takes a loooooot of place!
You can see some examples on the screenshot linked to the post.

Btw, there's no duplication in the files, so.. And no errors in logs about that.

Thanks anyway for your work! :D
**JOHNN1E**
![Capture d’écran 2023-07-07 061641](https://github.com/Wacky-Mole/WackysDatabase/assets/76440328/d20a1542-1361-4c03-9dcd-981c7adcf986)

**Comment by Wacky-Mole** [comment]
I am going to close this for now, but please test on b18 release. Should be out soon.
